a=1
b=2
if(a==1):
    if(b==1):
        print("1,1")
    elif(b==2):
        print("1,2")
    else:
        print("1,3")
elif(a==2):
    if(b==1):
        print("1,1")
    elif(b==2):
        print("1,2")
    else:
        print("1,3")
else:
    if(b==1):
        print("1,1")
    elif(b==2):
        print("1,2")
    else:
        print("1,3")
